#!/bin/bash
DEBUG=false
if ${DEBUG}; then
	echo Task I and Task II
	echo Design a database with plain .txt doc
	echo Design function and interface
	echo Add functions with an interactive interface to access these functions.
	echo The interface is selected, read input, and get the result of an operations.
	echo The output should be like as follow
	echo Welcome to my contact database, please select in the following menu:
	echo a. Find a record
	echo b. Add a new record
	echo c. Update a record
	echo d. Remove a record
	echo e. Quit
	echo Selection is: 

	echo Task III: Implementation
	echo Implement shell scripts to interact with the database management
fi
echo 
echo "Welcome to my contact database, please select in the following menu:"
echo "------------------------------------------------------------------"

choice="f"

menu="(a) Find a record
(b) Add a new record
(c) Update a record
(d) Remove a record
(e) Quit"


addRecord() {
  echo "------------"
  echo "Add a record"
  echo "------------"
  read -p "Enter a name: " name
  read -p "Enter an address: " address
  read -p "Enter a phone number: " phone
  read -p "Enter an email: " email
  echo "$name:$address:$phone:$email" >> database.txt
}


while [ "$choice" != "e" ]; do

	echo -n "$menu"
	echo
	read -p "> Your selection : " choice

	case $choice in 
		a) echo "Find a record";;
		  #echo "-------------"
		#A) echo "Find a record";;
		b)addRecord;;
		B)addRecord;;
		c) echo "Update a record";;
		   #echo "--------------"
		#C) echo "Update a record";;
		d) echo "Remove a record";;
		   #echo "---------------"
		#D) echo "Remove a record";;
		e) echo "The program is terminated..."
			exit 1;;
		*)
		echo "Invalid input, please enter (a-e)... "
		echo ;;
		
	esac
done

exit 0


