#!/bin/bash

choice="f"

menu="(a) Find a record
(b) Add a new record
(c) Update a recod
(d) Remove a recod
(e) Quit
> Your selection : "

while [ "$choice" != "e" ]; do

	echo -n "$menu"

	read choice
	case $choice in 
		a) echo "Find a record";;
		A) echo "Find a record";;
		b) echo "Add a record";;
		B) echo "Add a record";;
		c) echo "Update a record";;
		C) echo "Update a record";;
		d) echo "Remove a record";;
		D) echo "Remove a record";;
		e) exit;;
		E) exit
	esac
done

exit 0
