#!/bin/bash
DEBUG=false
if ${DEBUG}; then
	echo Design function and interface
	echo Add functions with an interactive interface to access these functions.
	echo The interface is selected, read input, and get the result of an operations.
	echo The output should be like as follow
	echo Welcome to my contact database, please select in the following menu:
	echo a. Find a record
	echo b. Add a new record
	echo c. Update a record
	echo d. Remove a record
	echo e. Quit
	echo :Selection is: 
fi
choice="f"

menu="(a) Find a record
(b) Add a new record
(c) Update a recod
(d) Remove a recod
(e) Quit
> Your selection : "

while [ "$choice" != "e" ]; do

	echo -n "$menu"

	read choice
	case $choice in 
		a) echo "Find a record";;
		A) echo "Find a record";;
		b) echo "Add a record";;
		B) echo "Add a record";;
		c) echo "Update a record";;
		C) echo "Update a record";;
		d) echo "Remove a record";;
		D) echo "Remove a record";;
		e) exit;;
		E) exit
	esac
done

exit 0
